name: DevSecOps CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.2

      - name: Terraform Init & Validate
        run: |
          terraform init
          terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

  security-scan:
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: tfsec - Scan Terraform for vulnerabilities
        uses: aquasecurity/tfsec-action@v1.0.0

      - name: Trivy - Scan Docker Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: your-dockerhub-username/your-image-name:latest

  sealed-secrets:
    runs-on: ubuntu-latest
    needs: security-scan

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Apply Sealed Secrets to Kubernetes
        run: |
          kubectl apply -f sealed-secret.yaml
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}